### ISSUE TITLE
Cannot configure httppost node in the configuration

### ISSUE THREAD

**Issue by aignas** [influxdata/ansible-kapacitor#1]
Once I tried using the `kapacitor_httppost` variable in my `playbook.yml`, I got this error when trying to run `kapacitor`:
```
 sudo -u kapacitor kapacitord -config /etc/kapacitor/kapacitor.conf

'##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::'########::
 ##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##: ##.... ##:
 ##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##: ##:::: ##:
 #####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##: ########::
 ##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##: ##.. ##:::
 ##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##: ##::. ##::
 ##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######:: ##:::. ##:
..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::

2017/12/18 13:27:41 Using configuration at: /etc/kapacitor/kapacitor.conf
[run] 2017/12/18 13:27:41 E! parse config: Near line 2 (last key parsed 'httppost.url'): expected key separator '=', but got ':' instead
run: parse config: Near line 2 (last key parsed 'httppost.url'): expected key separator '=', but got ':' instead
```

I think this is because the config file is in TOML and we are trying it to give JSON. I tried an alternative of specifying the `httppost` configuration similar to `influxdb` configuration, but then I get an error because the `kapacitor_httppost` is used to generate an empty array at the top of the configuration file. Once I remove the line
```
httppost = []
```
from the generated configuration file, everything starts working.

**Comment by pmyjavec** [comment]
Hello @aignas , thanks for pointing this out. I've resolved the now.

I've also made some pretty major change to the way the configuration is managed, there is now no need to pass in a `kapacitor_component_config` hash so the role will now be more simple to use. Please see the updated README and [this spec test config](https://github.com/influxdata/ansible-kapacitor/blob/master/test/integration/default/ansible/default.yml) to see how to use the role successfully.

If you have any trouble please don't hesitate to contact me right away. Thank you.
